### ISSUE TITLE
Installation error -arm64 - ubuntu18.04

### ISSUE THREAD

**Issue by jonatli1979** [jariarkko/cave-outliner#59]
Hi Jari, I get this error when running `make clean all`. I've tried `make` also.
all dependencies listed in installation instructions are installed. Any ideas?

Best regards,
Jon Atli

![Screenshot from 2021-11-23 10-40-22](https://user-images.githubusercontent.com/62761112/143009930-e10cac3f-1fcb-4b2d-bda8-3ee947ffe0e5.png)

**Comment by jariarkko** [comment]
I think this must be some version issue with the library vs. cave-outliner. But also seems to be an issue with this one constant, which also turns out to be not needed in the current software of cave-outliner.

Hold on, seeing if I can fix this.

**Comment by jariarkko** [comment]
Did that help?

**Comment by jariarkko** [comment]
(The software is being actively built, by the way. I’ve been silent but been hacking. Nearing the point where I can recognise entrances and start to feed cave surface fragments to AI process to recognise stalactites etc. Nevertheless, please ask for help if you are trying the software out. We’re still on the bleeding edge. The README has an example of usage which you may be able to follow. Try first with small resolution/step. If you run into issues, send mail!)

**Comment by jariarkko** [comment]
Hmm…. Probably some library version issue. I have run in Ubuntu 20, but not 18. 

But, that particular line is currently actually not needed. I fixed this error, can you test in your environment if it helped?

(The software is being actively built, by the way. I’ve been silent but been hacking. Nearing the point where I can recognise entrances and start to feed cave surface fragments to AI process to recognise stalactites etc. Nevertheless, please ask for help if you are trying the software out. We’re still on the bleeding edge. The README has an example of usage which you may be able to follow. Try first with small resolution/step. If you run into issues, send mail!)

Jari

**Comment by jonatli1979** [comment]
Solved :) 

Thanks Jari
